// Generated from apps/site/tokens.css by tools/build-packages.mjs — do not hand-edit.
// Colours resolve through CSS custom properties so Tailwind classes follow the active theme.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "action": "var(--action)",
        "on-action": "var(--on-action)",
        "action-hover": "var(--action-hover)",
        "accent-edge": "var(--accent-edge)",
        "paper": "var(--paper)",
        "surface": "var(--surface)",
        "surface-2": "var(--surface-2)",
        "surface-3": "var(--surface-3)",
        "ink": "var(--ink)",
        "ink-2": "var(--ink-2)",
        "ink-3": "var(--ink-3)",
        "rule": "var(--rule)",
        "rule-strong": "var(--rule-strong)",
        "accent": "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-ink": "var(--accent-ink)",
        "accent-wash": "var(--accent-wash)",
        "accent-critical": "var(--accent-critical)",
        "on-accent": "var(--on-accent)",
        "on-neg": "var(--on-neg)",
        "on-accent-sm": "var(--on-accent-sm)",
        "pos": "var(--pos)",
        "pos-wash": "var(--pos-wash)",
        "pend": "var(--pend)",
        "neg": "var(--neg)",
        "warn": "var(--warn)",
        "warn-wash": "var(--warn-wash)",
        "neg-wash": "var(--neg-wash)",
        "act-send": "var(--act-send)",
        "act-receive": "var(--act-receive)",
        "act-swap": "var(--act-swap)",
        "act-earn": "var(--act-earn)",
        "act-send-deep": "var(--act-send-deep)",
        "act-receive-deep": "var(--act-receive-deep)",
        "tx-received": "var(--tx-received)",
        "tx-sent": "var(--tx-sent)",
        "tx-swap": "var(--tx-swap)",
        "tx-earn": "var(--tx-earn)",
        "tx-faucet": "var(--tx-faucet)",
        "tx-glyph": "var(--tx-glyph)",
        "nav-pill": "var(--nav-pill)",
        "nav-bg": "var(--nav-bg)",
        "nav-ink-off": "var(--nav-ink-off)",
        "pat": "var(--pat)",
        "card-slate": "var(--card-slate)",
        "card-orange": "var(--card-orange)",
        "card-blue": "var(--card-blue)",
        "card-green": "var(--card-green)",
        "card-purple": "var(--card-purple)",
        "card-slate-deep": "var(--card-slate-deep)",
        "card-orange-deep": "var(--card-orange-deep)",
        "card-blue-deep": "var(--card-blue-deep)",
        "card-green-deep": "var(--card-green-deep)",
        "card-purple-deep": "var(--card-purple-deep)",
        "nav-rim": "var(--nav-rim)",
        "nav-rim-lo": "var(--nav-rim-lo)",
        "balance": "var(--balance)",
        "balance-deep": "var(--balance-deep)",
        "balance-fg": "var(--balance-fg)",
        "balance-fg-muted": "var(--balance-fg-muted)",
        "shadow-1": "var(--shadow-1)",
        "shadow-2": "var(--shadow-2)",
        "code-bg": "var(--code-bg)"
      },
      "spacing": {
        "1": "var(--sp-1)",
        "2": "var(--sp-2)",
        "3": "var(--sp-3)",
        "4": "var(--sp-4)",
        "5": "var(--sp-5)",
        "6": "var(--sp-6)",
        "8": "var(--sp-8)",
        "0-5": "var(--sp-0-5)",
        "1-5": "var(--sp-1-5)",
        "2-5": "var(--sp-2-5)",
        "3-5": "var(--sp-3-5)"
      },
      "borderRadius": {
        "sm": "var(--radius-sm)",
        "md": "var(--radius-md)",
        "lg": "var(--radius-lg)",
        "full": "var(--radius-full)",
        "device": "var(--radius-device)",
        "device-outer": "var(--radius-device-outer)"
      },
      "fontSize": {
        "body": "var(--t-body)",
        "label": "var(--t-label)",
        "caption": "var(--t-caption)",
        "cta": "var(--t-cta)",
        "balance": "var(--t-balance)",
        "display": "var(--t-display)",
        "title": "var(--t-title)",
        "heading": "var(--t-heading)",
        "subhead": "var(--t-subhead)"
      }
    }
  }
};
